steps:
  # 1. Build the Docker image from file
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-east1-docker.pkg.dev/qwiklabs-gcp-04-f3fb5187c45c/my-repo/my-app:${BUILD_ID}'
      - '.'

  # 2. Push the image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-east1-docker.pkg.dev/qwiklabs-gcp-04-f3fb5187c45c/my-repo/my-app:${BUILD_ID}'

options:
  logging: CLOUD_LOGGING_ONLY