apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend  # Deployment name changed to frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chai-frontend
  template:
    metadata:
      labels:
        app: chai-frontend
    spec:
      containers:
      - name: frontend  # Container name changed to frontend
        image: us-central1-docker.pkg.dev/project-e88d1c23-e44c-4d58-8dd/om-app-repo/order-frontend:latest
        ports:
        - containerPort: 80