apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: RootPassword123
  MYSQL_DATABASE: chaipolitics_db
  MYSQL_USER: chai_admin
  MYSQL_PASSWORD: UserPassword123